# Generated by Django 4.0 on 2021-02-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='zeus1',
        ),
    ]
